///////////////////////////////////////////////////////////////////////////////
// MC_CppServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_MC_Cpp = 0x3F000000;
#define SRVNAME_MC_CPP "MC_Cpp"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_MC_CppCAxis6 = {0xba44bbc5,0xf1b3,0x4d60,{0xb9,0x5a,0x65,0x00,0xe4,0xfd,0x99,0x0e}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Axis6Parameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Axis6Parameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} Axis6Parameter, *PAxis6Parameter;

#pragma pack(push,1)
typedef struct _Axis6Inputs
{
	ULONG Value;
	ULONG Status;
	ULONG Data;
	bool change;
} Axis6Inputs, *PAxis6Inputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _Axis6Outputs
{
	ULONG Value;
	ULONG Control;
	ULONG Data;
	SHORT icount;
	bool led1;
} Axis6Outputs, *PAxis6Outputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Axis6Inputs 0
#define ADI_Axis6Outputs 1
///</AutoGeneratedContent>
