///////////////////////////////////////////////////////////////////////////////
// MC_CppClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "MC_CppClassFactory.h"
#include "MC_CppServices.h"
#include "MC_CppVersion.h"
#include "Axis6.h"

BEGIN_CLASS_MAP(CMC_CppClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_MC_CppCAxis6, SRVNAME_MC_CPP "!CAxis6", CAxis6)
///</AutoGeneratedContent>
END_CLASS_MAP()

CMC_CppClassFactory::CMC_CppClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_MC_CPP)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(MC_Cpp));
#endif //defined(TCDBG_UNIT_VERSION)
}

